### ISSUE TITLE
Add on with Multiple/cluster  splunk  Search head 

### ISSUE THREAD

**Issue by idglabs** [Moh-Ayman/Splunk-TA-for-ApacheNifi-Monitoring#1]
Good morning,

This addon seem very interesting but I'm wondering how it;s work in Enterprise environment  when you have multiple search heads and as well multiple indexers  and data can be duplicated in splunk

Is there any solution to avoid duplicate data in splunk?
Thank you

**Comment by Moh-Ayman** [comment]
Hey, 

So, Splunk is built of multiple application tiers which are: 
1- Forwarders: to accept data from Source systems and storing it into the indexers
2- Indexers: to store the data and make it available to the search heads for the users to search the data
3- Search Heads: so that users are able to search data. 

Indexers could be in a cluster mode, where configuration are being set on the deployer and push at once to all the indexers in the indexer cluster. >> So that means that the data will be pushed distributed on the indexers in the indexer cluster. Where there is no duplication on the information level.

Then the search-heads, as well could be grouped in cluster where i access the indexer tier to search the data only. 

The Technical Addon to monitor the Nifi Installation will be placed in the UFs on the Nifi Cluster Nodes. Then UFs on the Nifi Cluster Nodes have to send their data to Splunk HFs Tier. Which will accept the data and ingest it to the Indexer Tier to make it available to the Search Heads so that the users can search the data. 

I hope this clarified how things is going!

I'm happy to support you if needed ;)!

Thank 
Br,
MK

**Comment by idglabs** [comment]
Thank you  very much , really appreciated your details.
